version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/jaeger:2.3.0
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.119.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./configs/otel-collector-config.yml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus  # Persisted storage
    environment:
      - PROMETHEUS_CONFIG_FILE=/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=15d"
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      # - grafana-data:/var/lib/grafana
      - ./configs/grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - jaeger-all-in-one

# volumes:
#   grafana-data:


  # # Alertmanager
  # alertmanager:
  #   image: prom/alertmanager:latest
  #   restart: always
  #   volumes:
  #     - ./configs/alertmanager.yml:/etc/alertmanager/alertmanager.yml
  #   ports:
  #     - "9093:9093"

  # # Rust Service
  # rust-webhook-service:
  #   build: ./server
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - otel-collector
