apiVersion: 1
datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-all-in-one:16686
    jsonData:
      tracesToLogs:
        datasourceUid: "Prometheus"
      spanBar:
        showDuration: true
    isDefault: false