[package]
name = "poll-program"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.12"
tokio = { version = "1.43.0", features = ["full"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"